export const data = JSON.parse("{\"key\":\"v-ea1b8e4a\",\"path\":\"/posts/%20git%20push%20fatal_%20The%20remote%20end%20hung%20up%20unexpectedly.html\",\"title\":\"git push fatal: The remote end hung up unexpectedly\",\"lang\":\"en-US\",\"frontmatter\":{\"author\":\"B4night\",\"date\":\"2024-02-05T00:00:00.000Z\",\"title\":\"git push fatal: The remote end hung up unexpectedly\",\"tags\":[],\"categories\":[\"Useful Skills\",\"git push fatal! The remote end hung up unexpectedly.md\"],\"description\":\"git push fatal: The remote end hung up unexpectedly stackoverflow link: https://stackoverflow.com/questions/15240815/git-fatal-the-remote-end-hung-up-unexpectedly This usually h...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://b4night.github.io/posts/%20git%20push%20fatal_%20The%20remote%20end%20hung%20up%20unexpectedly.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"B4night\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"git push fatal: The remote end hung up unexpectedly\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"git push fatal: The remote end hung up unexpectedly stackoverflow link: https://stackoverflow.com/questions/15240815/git-fatal-the-remote-end-hung-up-unexpectedly This usually h...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"B4night\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-02-05T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"git push fatal: The remote end hung up unexpectedly\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-02-05T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"B4night\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.25,\"words\":75},\"filePathRelative\":\"posts/ git push fatal: The remote end hung up unexpectedly.md\",\"localizedDate\":\"February 5, 2024\",\"excerpt\":\"\\n<p>stackoverflow link: <a href=\\\"https://stackoverflow.com/questions/15240815/git-fatal-the-remote-end-hung-up-unexpectedly\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://stackoverflow.com/questions/15240815/git-fatal-the-remote-end-hung-up-unexpectedly</a></p>\\n<p>This usually happens when the files we push exceeds buffer size. So we can manually change postBuffer size.</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
