export const data = JSON.parse("{\"key\":\"v-4daed234\",\"path\":\"/posts/CSS%20Learning.html\",\"title\":\"CSS Learning\",\"lang\":\"en-US\",\"frontmatter\":{\"author\":\"B4night\",\"date\":\"2024-01-26T00:00:00.000Z\",\"title\":\"CSS Learning\",\"categories\":[\"FrontEnd\",\"CSS\"],\"description\":\"CSS语法规则由两个主要的部分构成: 选择器以及一条或多条声明(样式) 外部样式 在html的<head>标签里面使用link标签来链接到css文件 <link rel=\\\"stylesheet\\\" type=\\\"text/css\\\" href=\\\"./template.css\\\"> 全局选择器 可以与任何元素匹配, 优先级最低, 一般做样式初始化 元素选择器 控...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://b4night.github.io/posts/CSS%20Learning.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"B4night\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"CSS Learning\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"CSS语法规则由两个主要的部分构成: 选择器以及一条或多条声明(样式) 外部样式 在html的<head>标签里面使用link标签来链接到css文件 <link rel=\\\"stylesheet\\\" type=\\\"text/css\\\" href=\\\"./template.css\\\"> 全局选择器 可以与任何元素匹配, 优先级最低, 一般做样式初始化 元素选择器 控...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"B4night\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-01-26T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"CSS Learning\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-01-26T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"B4night\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"基本语法\",\"slug\":\"基本语法\",\"link\":\"#基本语法\",\"children\":[]}],\"readingTime\":{\"minutes\":2.03,\"words\":608},\"filePathRelative\":\"posts/CSS Learning.md\",\"localizedDate\":\"January 26, 2024\",\"excerpt\":\"<p>CSS语法规则由两个主要的部分构成: 选择器以及一条或多条声明(样式)</p>\\n<h1>外部样式</h1>\\n<p>在html的<code>&lt;head&gt;</code>标签里面使用<code>link</code>标签来链接到css文件</p>\\n<p><code>&lt;link rel=\\\"stylesheet\\\" type=\\\"text/css\\\" href=\\\"./template.css\\\"&gt;</code></p>\\n<h1>全局选择器</h1>\\n<p>可以与任何元素匹配, 优先级最低, 一般做样式初始化</p>\\n<div class=\\\"language-css\\\" data-ext=\\\"css\\\" data-title=\\\"css\\\"><pre class=\\\"language-css\\\"><code><span class=\\\"token selector\\\">*</span><span class=\\\"token punctuation\\\">{</span>\\n    <span class=\\\"token property\\\">margin</span><span class=\\\"token punctuation\\\">:</span> 0<span class=\\\"token punctuation\\\">;</span>\\n    <span class=\\\"token property\\\">padding</span><span class=\\\"token punctuation\\\">:</span> 0<span class=\\\"token punctuation\\\">;</span>\\n<span class=\\\"token punctuation\\\">}</span>\\n</code></pre></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
