export const data = JSON.parse("{\"key\":\"v-e9da6f7c\",\"path\":\"/posts/JS%20Video%20Learn.html\",\"title\":\"JS Video Learn\",\"lang\":\"en-US\",\"frontmatter\":{\"author\":\"B4night\",\"date\":\"2024-01-25T00:00:00.000Z\",\"title\":\"JS Video Learn\",\"categories\":[\"FrontEnd\",\"JavaScript\",\"Language\"],\"description\":\"Output solutions Array.join() 将所有的数组成员连接为一个string返回 如果提供参数, 则分割符为参数, 否则为逗号 使用数组的join和字符串的split, 可以实现数组和字符串的互换 Array.reverse() 这是一个原地函数, 会修改数组的值 \",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://b4night.github.io/posts/JS%20Video%20Learn.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"B4night\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"JS Video Learn\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Output solutions Array.join() 将所有的数组成员连接为一个string返回 如果提供参数, 则分割符为参数, 否则为逗号 使用数组的join和字符串的split, 可以实现数组和字符串的互换 Array.reverse() 这是一个原地函数, 会修改数组的值 \"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"B4night\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-01-25T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"JS Video Learn\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-01-25T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"B4night\\\"}]}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.33,\"words\":99},\"filePathRelative\":\"posts/JS Video Learn.md\",\"localizedDate\":\"January 25, 2024\",\"excerpt\":\"\\n<div class=\\\"language-javascript\\\" data-ext=\\\"js\\\" data-title=\\\"js\\\"><pre class=\\\"language-javascript\\\"><code><span class=\\\"token function\\\">alert</span><span class=\\\"token punctuation\\\">(</span><span class=\\\"token string\\\">\\\"content\\\"</span><span class=\\\"token punctuation\\\">)</span><span class=\\\"token punctuation\\\">;</span>\\n\\ndocument<span class=\\\"token punctuation\\\">.</span><span class=\\\"token function\\\">write</span><span class=\\\"token punctuation\\\">(</span><span class=\\\"token string\\\">\\\"content\\\"</span><span class=\\\"token punctuation\\\">)</span><span class=\\\"token punctuation\\\">;</span>\\n\\nconsole<span class=\\\"token punctuation\\\">.</span><span class=\\\"token function\\\">log</span><span class=\\\"token punctuation\\\">(</span><span class=\\\"token string\\\">\\\"content\\\"</span><span class=\\\"token punctuation\\\">)</span><span class=\\\"token punctuation\\\">;</span>\\n</code></pre></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
